[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "libmysqlclient", "nginx"]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs --no-dev --optimize-autoloader"
]

[phases.build]
cmds = []

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"

